// <auto-generated />
using System;
using CSMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSMS.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSMS.Models.Officer", b =>
                {
                    b.Property<int>("officer_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("officer_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("officer_emp_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("officer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("officer_password")
                        .IsRequired()
                        .HasColumnType("binary(64)");

                    b.Property<string>("officer_workplace")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("officer_id");

                    b.ToTable("Officers");
                });
#pragma warning restore 612, 618
        }
    }
}
